tap "anomalyco/tap"
tap "azure/azd"
tap "infisical/get-cli"
tap "market-dot-dev/tap", trusted: true
tap "yakitrak/yakitrak"

brew "zstd"
brew "gcalcli"
brew "azure-cli"
brew "bat"
brew "cloc"
brew "cloudflare-speed-cli"
brew "cocoapods"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "git-cliff"
brew "htop"
brew "jq"
brew "kcat"
brew "lazygit"
brew "lefthook"
brew "libpq", link: true
brew "webp"
brew "lsd"
brew "mole"
brew "ncdu"
brew "neovim"
brew "node"
brew "postgresql@16"
brew "python@3.12"
brew "rbenv"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "zoxide"
brew "zsh-syntax-highlighting"
brew "infisical/get-cli/infisical", trusted: true
brew "market-dot-dev/tap/traces"

cask "devtunnel"
cask "ghostty"
cask "ngrok"
cask "obs"
